-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied= 'Yes'
	AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Avg Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
	COUNT(customer_id) AS total_customer, 
	ROUND(AVG(purchase_amount), 2) AS avg_spend,
	ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer	
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
	SELECT customer_id, 
		previous_purchases,
		CASE
	 		WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segment
	FROM customer)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
	SELECT category, 
		item_purchased, 
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
	FROM customer
	GROUP BY category, item_purchased
) 
SELECT item_rank, category, item_purchased, total_orders 
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;	

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

--Q11. Which product categories contribute the most to total revenue?
WITH category_revenue AS (
    SELECT
        category,
        SUM(purchase_amount) AS total_revenue
    FROM customer
    GROUP BY category
)
SELECT
    category,
    total_revenue,
    ROUND(
        100.0 * total_revenue / SUM(total_revenue) OVER (),
        2
    ) AS revenue_percentage
FROM category_revenue
ORDER BY total_revenue DESC;


--Q.12 Does using a discount correlate with lower purchase amounts?
SELECT
    category,
    ROUND(
        AVG(
            CASE
                WHEN discount_applied = 'Yes'
                THEN purchase_amount
            END
        ),
        2
    ) AS avg_discounted_purchase,
    ROUND(
        AVG(
            CASE
                WHEN discount_applied = 'No'
                THEN purchase_amount
            END
        ),
        2
    ) AS avg_non_discounted_purchase,
    ROUND(
        AVG(
            CASE
                WHEN discount_applied = 'Yes'
                THEN purchase_amount
            END
        )
        -
        AVG(
            CASE
                WHEN discount_applied = 'No'
                THEN purchase_amount
            END
        ),
        2
    ) AS average_difference
FROM customer
GROUP BY category
ORDER BY average_difference DESC;

--Q. 13 What percentage of revenue comes from the highest-spending categories?
WITH category_revenue AS (
    SELECT
        category,
        SUM(purchase_amount) AS total_revenue
    FROM customer
    GROUP BY category
),
revenue_analysis AS (
    SELECT
        category,
        total_revenue,

        SUM(total_revenue) OVER (
            ORDER BY total_revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_revenue,
        SUM(total_revenue) OVER () AS overall_revenue
    FROM category_revenue
)
SELECT
    category,
    total_revenue,
    ROUND(
        100.0 * total_revenue / overall_revenue,
        2
    ) AS revenue_percentage,

    ROUND(
        100.0 * cumulative_revenue / overall_revenue,
        2
    ) AS cumulative_revenue_percentage

FROM revenue_analysis
ORDER BY total_revenue DESC;
